version: '3'
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python3 /app/as_bot_championship/bot/main.py

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data