from atomskills_org_bot.db.tables import Location, Option, Service, Hall

halls = [Hall(name=f"Павильон №{num}") for num in range(1, 5)]

locations = [
    Location(name="Изготовление прототипов", hall_id=1),
    Location(name="Каракури", hall_id=1),
    Location(name="Промышленная автоматика", hall_id=1),
    Location(name="Промышленная механика и монтаж", hall_id=1),
    Location(name="Работы на токарных станках", hall_id=1),
    Location(name="Работы на фрезерных станках", hall_id=1),
    Location(name="Сварочные технологии", hall_id=1),
    Location(name="Технологии композитов", hall_id=1),
    Location(name="Токарные работы на станках с ЧПУ", hall_id=1),
    Location(name="Фрезерные работы на станках с ЧПУ", hall_id=1),
    Location(name="Электромонтаж", hall_id=1),
    Location(name="Электроника", hall_id=1),
    Location(name="Аддитивные технологии", hall_id=2),
    Location(name="Вывод из экспл. объектов атом. энергии", hall_id=2),
    Location(name="Инженерный дизайн CAD", hall_id=2),
    Location(name="Инженерное проектирование", hall_id=2),
    Location(name="Инженер-технолог машиностроения", hall_id=2),
    Location(name="Квантовые технологии (СП Квант)", hall_id=2),
    Location(name="Неразрушающий контроль", hall_id=2),
    Location(name="Охрана окружающей среды", hall_id=2),
    Location(name="Охрана труда", hall_id=2),
    Location(name="Программная роботизация", hall_id=2),
    Location(name="Сметное дело", hall_id=2),
    Location(name="Строительный контроль", hall_id=2),
    Location(name="Тех.системы энергетических объектов", hall_id=2),
    Location(name="Цифровое ПСР предприятие", hall_id=2),
    Location(name="Анал.контроль (лаб-хим анализ)", hall_id=3),
    Location(name="Информационная безопасность", hall_id=3),
    Location(name="Корп. защита от внутр. угроз без-ти", hall_id=3),
    Location(name="Математическое моделирование", hall_id=3),
    Location(name="Машинное обучение и большие данные", hall_id=3),
    Location(name="Мехатроника", hall_id=3),
    Location(name="Обслуживание оборуд. релейной защиты", hall_id=3),
    Location(name="Программные решения для бизнеса", hall_id=3),
    Location(name="Сетевое и сис. администрирование", hall_id=3),
    Location(name="Управление жизненным циклом", hall_id=3),
    Location(name="Управление качеством", hall_id=3),
    Location(name="Управ. комм-ми/Антикриз. реаг-ие", hall_id=3),
    Location(name="Бетонные строительные работы", hall_id=4),
    Location(name="Водитель спец.автомобиля", hall_id=4),
    Location(name="Геодезия", hall_id=4),
    Location(name="Радиационный контроль", hall_id=4),
]

services = [
    Service(name="Обеспечение компетенции", chat_id=-1002333630229),
    Service(name="Вода", chat_id=-1002325854292),
    Service(name="Электрики", chat_id=-1002449940697),
    # Service(name="Вентиляция, канализация, сжатый воздух", chat_id=-1002165063549),
    # Service(name="Мебель, звук, ТВ", chat_id=-1002236001568),
    # Service(name="Сеть, интернет и ИТ", chat_id=-1002171181624),
    # Service(name="Безопасность", chat_id=-1002245706143),
    # Service(name="Цифровая платформа", chat_id=-1002155264156),
    # Service(name="Орг. комитет чемпионата ", chat_id=-1002220850821),
]


options = [
    Option(name="Нужны расходные материалы", comment="", service_id=1),
    Option(name="Нужны инструменты", comment="", service_id=1),
    Option(name="Нужны канцтовары", comment="", service_id=1),
    Option(name="Иное", comment="", service_id=1),
    Option(name="Нужна вода в бутылках 19 л", comment="", service_id=2),
    Option(name="Нужны стаканчики для воды", comment="", service_id=2),
    Option(name="Нужна бутилированная вода", comment="", service_id=2),
    Option(name="Иное", comment="", service_id=2),
    Option(name="Пропало электричество в розетке 220V", comment="", service_id=3),
    Option(name="Пропало электричество в розетке 380V", comment="", service_id=3),
    Option(name="Установить доп. розетки", comment="", service_id=3),
    Option(name="Требуется инженер-электрик", comment="", service_id=3),
    Option(name="Иное", comment="", service_id=3),
    # Option(name="Проблемы с вентиляцией", comment="", service_id=4),
    # Option(name="Проблема со стенами", comment="", service_id=4),
    # Option(name="Проблема с сжатым воздухом", comment="", service_id=4),
    # Option(name="Проблема с канализацией", comment="", service_id=4),
    # Option(name="Иное", comment="", service_id=4),
    # Option(name="Нехватка мебели", comment="", service_id=5),
    # Option(name="Сломанная мебель", comment="", service_id=5),
    # Option(name="Проблема с ТВ", comment="", service_id=5),
    # Option(name="Проблема со звуком/микрофоном", comment="", service_id=5),
    # Option(name="Иное", comment="", service_id=5),
    # Option(name="Проблема с МФУ", comment="", service_id=6),
    # Option(name="Проблема с компьютером", comment="", service_id=6),
    # Option(name="Нет интернета (проводное подкл.)", comment="", service_id=6),
    # Option(name="Нет интернета (wi-fi)", comment="", service_id=6),
    # Option(name="Поврежден сетевой кабель", comment="", service_id=6),
    # Option(name="Иное", comment="", service_id=6),
    # Option(name="Охрана", comment="", service_id=7),
    # Option(name="Группа быстрого реагирования", comment="", service_id=7),
    # Option(name="Иное", comment="", service_id=7),
    # Option(name="Проблема с выставлением оценок", comment="", service_id=8),
    # Option(name="Не работает функция на платформе", comment="", service_id=8),
    # Option(name="Иное", comment="", service_id=8),
    # Option(name="Уборка компетенции", comment="", service_id=9),
    # Option(name="Компетенция не убрана с прошлого дня", comment="", service_id=9),
    # Option(name="Требуется уборка прямо сейчас", comment="", service_id=9),
]
